### ISSUE TITLE
[bug]: Attempting to play audio throws a FirebaseError

### ISSUE THREAD

**Issue by IncognitoTGT** [quran/quran.com-frontend-next#2176]
### Is there an existing issue for this?

- [X] There is no exsiting issue for this bug

### Describe the bug

When I attempt to play audio of a surah, it gives a generic "Something went wrong error." In the console, it shows this error:
![Screenshot 2024-06-22 at 16 50 51](https://github.com/quran/quran.com-frontend-next/assets/72108630/96e6ac4d-60a0-4e1d-a68d-567273896efe)

### Relevant log output

```shell
_app-be212011ea2f941f.js:1 Uncaught (in promise) 
FirebaseError: Installations: Could not process request. Application offline. (installations/app-offline).
    at _app-be212011ea2f941f.js:1:473816
    at _app-be212011ea2f941f.js:1:474775
    at Rt (_app-be212011ea2f941f.js:1:473446)
    at async Nt (_app-be212011ea2f941f.js:1:473588)
    at async _app-be212011ea2f941f.js:1:477618
    at async Promise.all (index 1)
    at async ln (_app-be212011ea2f941f.js:1:485274)
    at async _app-be212011ea2f941f.js:1:488259
```

### Steps to reproduce

1. Go to any surah
2. attempt to play audio
3. Aforementioned log shows in console.

### Environment (please complete the following information) and Add any other context about this bug

OS: MacOS 15
Browser: Arc Browser (chromium based)
Version: Chromium version 126.0.6478.57

### Environment

All 3 have the same issue

**Comment by IncognitoTGT** [comment]
Issue seems to have been resolved
